spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio_stone
    username: postgres
    password:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
